### PR TITLE
Tidy examples

### PR DESCRIPTION
**Pull request by itamarcaspi**
I really like the datasets and examples you kindly provide with your book, and I plan to use many of them in my [ml4econ course](ml4econ.rbind.io). I am also a big fan of the tidyverse, so I've decided to give your code the "tidy" touch, starting with the spam example. The code is meant to be as reproducible as possible. 

Btw. `spam.R` sources a function named `deviance.R` which is not present in the examples folder. Where can I find it? I can guess what it does, but I'd like to write it down as accurately as possible.

### CODE REVIEW

**Comment by mataddy** [comment]
cool!!  @itamarcaspi thanks this is great.  I want to get the directory ready for more notebook examples, because I know of others that are inbound from people teaching.  Can you please create a /notebook folder at the root and then put tidy-examples inside there?

**Comment by itamarcaspi** [comment]
Sure. Will do. Thanks!

**Comment by itamarcaspi** [comment]
Hi,

I've added the OOS R^2 section (the tidy way) created the `/notebooks` folder and moved everything there.

**Comment by mataddy** [comment]
Thanks @itamarcaspi, this is great.

**Comment by mataddy** [comment]
and @itamarcaspi I added deviance.R

**Pull request merged**
